version: '3'

services:
  db:
    container_name: $MYSQL_CONTAINER_NAME
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
  pma:
    container_name: $PMA_CONTAINER_NAME
    image: phpmyadmin/phpmyadmin
    ports:
      - $PMA_CONTAINER_PORT:80
    environment:
      - PMA_HOST=$MYSQL_CONTAINER_NAME

networks:
  default:
    external:
      name: $NETWORK_NAME
